# Generated by Django 5.0.3 on 2024-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='owner',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
