# Generated by Django 5.0.3 on 2024-04-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_todoitem_owner_notifications'),
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
