# Generated by Django 5.0.3 on 2024-05-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_notification_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='task',
        ),
    ]
